export enum SessionState {
  OPEN = "OPEN",
  OPEN_VERIFIED = "OPEN_VERIFIED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  PAID = "PAID",
  COMPLETED = "COMPLETED",
  WALKOUT = "WALKOUT",
  EXPIRED = "EXPIRED",
  FORCE_CLOSED = "FORCE_CLOSED",
}

export enum OrderState {
  PLACED_UNVERIFIED = "PLACED_UNVERIFIED",
  PLACED_VERIFIED = "PLACED_VERIFIED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  PREPARING = "PREPARING",
  READY = "READY",
  SERVED = "SERVED",
  CANCELLED = "CANCELLED",
}

export enum PaymentMethod {
  RAZORPAY_GATEWAY = "RAZORPAY_GATEWAY",
  CASH = "CASH",
  RESTAURANT_POS = "RESTAURANT_POS",
  EXTERNAL_UPI = "EXTERNAL_UPI",
}

export enum PaymentStatus {
  PENDING_CONFIRMATION = "PENDING_CONFIRMATION",
  CONFIRMED = "CONFIRMED",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum StaffRole {
  WAITER = "WAITER",
  CASHIER = "CASHIER",
  KITCHEN = "KITCHEN",
  GUARD = "GUARD",
  MANAGER = "MANAGER",
  RESTAURANT_ADMIN = "RESTAURANT_ADMIN",
  RESTAURANT_OWNER = "RESTAURANT_OWNER",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum ExitPassStatus {
  ISSUED = "ISSUED",
  VERIFIED = "VERIFIED",
  EXPIRED = "EXPIRED",
  REVOKED = "REVOKED",
}
